server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: eureka-client-coupon-distribution
  datasource:
    # 数据源
    url: jdbc:mysql://123.60.182.220:3306/coupon_data?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: UYeR1byMDVvhvvpxUf5z1hlI1D
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CouponHikariCP
  redis:
    database: 1
    host: 123.60.182.220
    port: 6379
    password: UYeR1byMDVvhvvpxUf5z1hlI1D
    # 连接超时时间
    timeout: 10000
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    consumer:
#      group-id: coupon-x
#      auto-offset-reset: latest
  # 开启 ribbon 重试机制, 即获取服务失败是否从另外一个节点重试
  cloud:
    loadbalancer:
      retry:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

logging:
  level:
    com.weng.coupon: debug
  config: classpath:log4j2.xml

# feign 相关的配置
feign:
  hystrix:
    enabled: true   # Hystrix 默认是关闭的
  client:
    config:
      default:  # 全局的
        connectTimeout: 2000  # 默认的连接超时时间是 10s
        readTimeout: 5000
      eureka-client-coupon-template:  # 单独服务的配置
        connectTimeout: 3000  # 默认的连接超时时间是 10s
        readTimeout: 5000
